name: Build

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract Ruby version from mise.toml
      id: ruby-version
      run: |
        ruby_version=$(grep '^ruby = ' mise.toml | sed 's/ruby = "\(.*\)"/\1/')
        echo "version=$ruby_version" >> $GITHUB_OUTPUT

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.ruby-version.outputs.version }}
        bundler-cache: true

    - name: Run tests
      run: make test-all

    - name: Run lint
      run: make lint

    - name: Build gem
      run: gem build worktreegroup.gemspec

    - name: Install gem locally
      run: gem install *.gem

    - name: Test CLI installation
      run: |
        worktreegroup version
        worktreegroup --help