name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Extract Ruby version from mise.toml
      id: ruby-version
      run: |
        ruby_version=$(grep '^ruby = ' mise.toml | sed 's/ruby = "\(.*\)"/\1/')
        echo "version=$ruby_version" >> $GITHUB_OUTPUT

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.ruby-version.outputs.version }}
        bundler-cache: true

    - name: Run tests
      run: make test-all

    - name: Configure gem credentials for GitHub Packages
      run: |
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :github: Bearer ${{ secrets.GITHUB_TOKEN }}
        EOF
        chmod 0600 ~/.gem/credentials

    - name: Build and publish gem to GitHub Packages
      run: |
        gem build worktreegroup.gemspec
        gem push --key github --host https://rubygems.pkg.github.com/nasustim *.gem
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}